name: ghlapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.8
  provider: 6.1.5+1
  http: 1.5.0
  permission_handler: 12.0.1
  geolocator: 14.0.2
  shared_preferences: 2.5.3
  device_info_plus: 11.5.0
  another_telephony: 0.4.1
  pin_code_fields: 8.0.1
  connectivity_plus: 6.1.5
  syncfusion_flutter_charts: 31.1.17
  google_sign_in: 6.1.5
  flutter_facebook_auth: 6.0.3
  flutter_widget_from_html_core: 0.14.11
  url_launcher: 6.2.1
  intl: 0.20.2
  video_player: 2.10.0
  pdf: 3.11.3
  path_provider: 2.1.5
  open_filex: 4.7.0
  csv: 6.0.0
  share_plus:
  file_picker: 10.3.2



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/images/
     - assets/images/bottom_nav_image/
     - assets/fonts/


  fonts:
     - family: Poppins
       fonts:
         - asset: assets/fonts/Poppins-Light.ttf
           weight: 300
         - asset: assets/fonts/Poppins-Regular.ttf
           weight: 400
         - asset: assets/fonts/Poppins-Medium.ttf
           weight: 500
         - asset: assets/fonts/Poppins-SemiBold.ttf
           weight: 600
         - asset: assets/fonts/Poppins-Bold.ttf
           weight: 700


